---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность участвовать  в соревновании с другим пользователем
  - Пользователь должен иметь возможность участвовать  в соревновании с ботом
  - Пользователь должен иметь возможность участвовать  в соревновании с другим пользователем по ссылке
  - Участники игры видят код соперника в режиме реального времени
  - Пользователь должен иметь возможность выбрать язык программирования из списка
  - При создании игры пользователь должен иметь возможность выбрать параметры игры (уровень сложности, тип игры, время, выбрать задачу)
non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Cайт должен быть разработан с учетом удобства использования
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность быстрого перехода на домашнюю страницу по клику на логотип
  - Пользователь должен иметь возможность участвовать в игре без регистрации
  - Пользователь должен иметь возможноть зарегистрироваться с помощью сторонних сервисов (Дискорт и Гитхаб)
